//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstiloLibreFront.Traducciones.TrErrores {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TrErrores {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TrErrores() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EstiloLibreFront.Traducciones.TrErrores.TrErrores", typeof(TrErrores).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Houbo un erro..
        /// </summary>
        public static string ERR_AddNew {
            get {
                return ResourceManager.GetString("ERR_AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario ou contrasinal incorrectos.
        /// </summary>
        public static string ERR_CrendencialesInvalidas {
            get {
                return ResourceManager.GetString("ERR_CrendencialesInvalidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Houbo un erro durante a eliminación..
        /// </summary>
        public static string ERR_Delete {
            get {
                return ResourceManager.GetString("ERR_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Erro na eliminación.
        /// </summary>
        public static string ERR_Eliminacion {
            get {
                return ResourceManager.GetString("ERR_Eliminacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a As datas seleccionadas deben ser anteriores ao día actual.
        /// </summary>
        public static string ERR_FechaActualNoValida {
            get {
                return ResourceManager.GetString("ERR_FechaActualNoValida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Data coñecemento&quot; e &quot;Hora aviso&quot; non son compatibles.
        /// </summary>
        public static string ERR_FechaNotiIncompatibleFechaIncidencia {
            get {
                return ResourceManager.GetString("ERR_FechaNotiIncompatibleFechaIncidencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Data coñecemento&quot; e &quot;Hora chegada&quot; non son compatibles.
        /// </summary>
        public static string ERR_FechaNotiIncompatibleHrLLegadaServM {
            get {
                return ResourceManager.GetString("ERR_FechaNotiIncompatibleHrLLegadaServM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Data coñecemento&quot; e &quot;Hora saída&quot; non son compatibles.
        /// </summary>
        public static string ERR_FechaNotiIncompatibleHrSalidaServM {
            get {
                return ResourceManager.GetString("ERR_FechaNotiIncompatibleHrSalidaServM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Non hai máis rexistros.
        /// </summary>
        public static string ERR_FinalizacionListaRegistros {
            get {
                return ResourceManager.GetString("ERR_FinalizacionListaRegistros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Existen erros no formulario.
        /// </summary>
        public static string ERR_FormConErrores {
            get {
                return ResourceManager.GetString("ERR_FormConErrores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Erro no gardado.
        /// </summary>
        public static string ERR_Guardado {
            get {
                return ResourceManager.GetString("ERR_Guardado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incongruencia con &quot;Data incidencia&quot;.
        /// </summary>
        public static string ERR_IncongruenciaConFechaIncidencia {
            get {
                return ResourceManager.GetString("ERR_IncongruenciaConFechaIncidencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incongruencia con &quot;Hora incidencia&quot;.
        /// </summary>
        public static string ERR_IncongruenciaConHoraIncidencia {
            get {
                return ResourceManager.GetString("ERR_IncongruenciaConHoraIncidencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incongruencia nas datas.
        /// </summary>
        public static string ERR_IncongruenciaFechas {
            get {
                return ResourceManager.GetString("ERR_IncongruenciaFechas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incongruencia nas horas.
        /// </summary>
        public static string ERR_IncongruenciaHoras {
            get {
                return ResourceManager.GetString("ERR_IncongruenciaHoras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a O campo está incompleto ou ten un valor non válido..
        /// </summary>
        public static string ERR_InputImporte_ {
            get {
                return ResourceManager.GetString("ERR_InputImporte ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Máximo 3 díxitos.
        /// </summary>
        public static string ERR_Max3Digitos {
            get {
                return ResourceManager.GetString("ERR_Max3Digitos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enche mínimo un campo.
        /// </summary>
        public static string ERR_Min1Campo {
            get {
                return ResourceManager.GetString("ERR_Min1Campo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a O valor mínimo debe ser 1.
        /// </summary>
        public static string ERR_MinValor1 {
            get {
                return ResourceManager.GetString("ERR_MinValor1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Os subcampos son obrigatorios.
        /// </summary>
        public static string ERR_NoCamposVacios {
            get {
                return ResourceManager.GetString("ERR_NoCamposVacios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a O número debe ser enteiro.
        /// </summary>
        public static string ERR_NumeroEntero {
            get {
                return ResourceManager.GetString("ERR_NumeroEntero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número non válido.
        /// </summary>
        public static string ERR_NumNoValido {
            get {
                return ResourceManager.GetString("ERR_NumNoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Obrigatorio.
        /// </summary>
        public static string ERR_Obligatorio {
            get {
                return ResourceManager.GetString("ERR_Obligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Houbo un erro durante o gardado..
        /// </summary>
        public static string ERR_SaveData {
            get {
                return ResourceManager.GetString("ERR_SaveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a O servidor devolveu un erro. Inténteo de novo e se o problema persiste póñase en contacto co equipo de soporte..
        /// </summary>
        public static string ERR_Servidor {
            get {
                return ResourceManager.GetString("ERR_Servidor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vostede non ten permisos suficientes para realizar a acción solicitada..
        /// </summary>
        public static string ERR_Servidor_403_Prohibido {
            get {
                return ResourceManager.GetString("ERR_Servidor_403_Prohibido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Houbo un erro durante a recuperación do rexistro..
        /// </summary>
        public static string ERR_ShowData {
            get {
                return ResourceManager.GetString("ERR_ShowData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a O campo está incompleto ou ten un valor non válido..
        /// </summary>
        public static string ERR_Validacion {
            get {
                return ResourceManager.GetString("ERR_Validacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Erro.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fallo rexistrado.
        /// </summary>
        public static string Fallo {
            get {
                return ResourceManager.GetString("Fallo", resourceCulture);
            }
        }
    }
}
