//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstiloLibreFront.Traducciones.TrGeneral {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TrGeneral {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TrGeneral() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EstiloLibreFront.Traducciones.TrGeneral.TrGeneral", typeof(TrGeneral).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a abril.
        /// </summary>
        public static string abril {
            get {
                return ResourceManager.GetString("abril", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear novo.
        /// </summary>
        public static string aCrearNuevo {
            get {
                return ResourceManager.GetString("aCrearNuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a agosto.
        /// </summary>
        public static string agosto {
            get {
                return ResourceManager.GetString("agosto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        public static string btnBuscador {
            get {
                return ResourceManager.GetString("btnBuscador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string btnEliminar {
            get {
                return ResourceManager.GetString("btnEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gardar.
        /// </summary>
        public static string btnGuardar {
            get {
                return ResourceManager.GetString("btnGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Limpar.
        /// </summary>
        public static string btnLimpiar {
            get {
                return ResourceManager.GetString("btnLimpiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Novo.
        /// </summary>
        public static string btnNuevo {
            get {
                return ResourceManager.GetString("btnNuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a do.
        /// </summary>
        public static string de {
            get {
                return ResourceManager.GetString("de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a decembro.
        /// </summary>
        public static string diciembre {
            get {
                return ResourceManager.GetString("diciembre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a domingo.
        /// </summary>
        public static string domingo {
            get {
                return ResourceManager.GetString("domingo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a xaneiro.
        /// </summary>
        public static string enero {
            get {
                return ResourceManager.GetString("enero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rexistrouse un fallo na/s seguinte/s máquina/s: .
        /// </summary>
        public static string FalloMaquinaRegistrado {
            get {
                return ResourceManager.GetString("FalloMaquinaRegistrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a febreiro.
        /// </summary>
        public static string febrero {
            get {
                return ResourceManager.GetString("febrero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a xoves.
        /// </summary>
        public static string jueves {
            get {
                return ResourceManager.GetString("jueves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a xullo.
        /// </summary>
        public static string julio {
            get {
                return ResourceManager.GetString("julio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a xuño.
        /// </summary>
        public static string junio {
            get {
                return ResourceManager.GetString("junio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        public static string lblAceptar {
            get {
                return ResourceManager.GetString("lblAceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string lblCancelar {
            get {
                return ResourceManager.GetString("lblCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descoñecido.
        /// </summary>
        public static string lblDesconocido {
            get {
                return ResourceManager.GetString("lblDesconocido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entendido.
        /// </summary>
        public static string lblEntendido {
            get {
                return ResourceManager.GetString("lblEntendido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data final.
        /// </summary>
        public static string lblFechaFinal {
            get {
                return ResourceManager.GetString("lblFechaFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data inicial.
        /// </summary>
        public static string lblFechaInicial {
            get {
                return ResourceManager.GetString("lblFechaInicial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Non.
        /// </summary>
        public static string lblNo {
            get {
                return ResourceManager.GetString("lblNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre (castellano).
        /// </summary>
        public static string lblNombreCastellano {
            get {
                return ResourceManager.GetString("lblNombreCastellano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nome (galego).
        /// </summary>
        public static string lblNombreGallego {
            get {
                return ResourceManager.GetString("lblNombreGallego", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si.
        /// </summary>
        public static string lblSi {
            get {
                return ResourceManager.GetString("lblSi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver máis.
        /// </summary>
        public static string lblVerMas {
            get {
                return ResourceManager.GetString("lblVerMas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar contrasinal.
        /// </summary>
        public static string liContraCabecera {
            get {
                return ResourceManager.GetString("liContraCabecera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar idioma.
        /// </summary>
        public static string liIdiomaCabecera {
            get {
                return ResourceManager.GetString("liIdiomaCabecera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pechar sesión.
        /// </summary>
        public static string liSesionCabecera {
            get {
                return ResourceManager.GetString("liSesionCabecera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a luns.
        /// </summary>
        public static string lunes {
            get {
                return ResourceManager.GetString("lunes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a martes.
        /// </summary>
        public static string martes {
            get {
                return ResourceManager.GetString("martes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a marzo.
        /// </summary>
        public static string marzo {
            get {
                return ResourceManager.GetString("marzo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a maio.
        /// </summary>
        public static string mayo {
            get {
                return ResourceManager.GetString("mayo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a mércores.
        /// </summary>
        public static string miércoles {
            get {
                return ResourceManager.GetString("miércoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Panel de control.
        /// </summary>
        public static string msjFallosMaquina {
            get {
                return ResourceManager.GetString("msjFallosMaquina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desexa extender a sesión?.
        /// </summary>
        public static string msjSesionCaducada {
            get {
                return ResourceManager.GetString("msjSesionCaducada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a novembro.
        /// </summary>
        public static string noviembre {
            get {
                return ResourceManager.GetString("noviembre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a outubro.
        /// </summary>
        public static string octubre {
            get {
                return ResourceManager.GetString("octubre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscador.
        /// </summary>
        public static string pTituloBuscador {
            get {
                return ResourceManager.GetString("pTituloBuscador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos tráfico.
        /// </summary>
        public static string pTituloDatosTrafico {
            get {
                return ResourceManager.GetString("pTituloDatosTrafico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Xeración listado.
        /// </summary>
        public static string pTituloListado {
            get {
                return ResourceManager.GetString("pTituloListado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menú.
        /// </summary>
        public static string pTituloMenu {
            get {
                return ResourceManager.GetString("pTituloMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proto Peaxes.
        /// </summary>
        public static string pTituloNav {
            get {
                return ResourceManager.GetString("pTituloNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Panel de control.
        /// </summary>
        public static string pTituloPanelControl {
            get {
                return ResourceManager.GetString("pTituloPanelControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rexistro.
        /// </summary>
        public static string pTituloRegistro {
            get {
                return ResourceManager.GetString("pTituloRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sábado.
        /// </summary>
        public static string sábado {
            get {
                return ResourceManager.GetString("sábado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a setembro.
        /// </summary>
        public static string septiembre {
            get {
                return ResourceManager.GetString("septiembre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administrar.
        /// </summary>
        public static string spanAdministracionNav {
            get {
                return ResourceManager.GetString("spanAdministracionNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rexistro anterior.
        /// </summary>
        public static string spanAnteriorRegistro {
            get {
                return ResourceManager.GetString("spanAnteriorRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sinalizacións.
        /// </summary>
        public static string spanAvisoNav {
            get {
                return ResourceManager.GetString("spanAvisoNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar grupo.
        /// </summary>
        public static string spanBuscadorGrupos {
            get {
                return ResourceManager.GetString("spanBuscadorGrupos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscador.
        /// </summary>
        public static string spanBuscadorNav {
            get {
                return ResourceManager.GetString("spanBuscadorNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar datos.
        /// </summary>
        public static string spanBuscadorTablasTipos {
            get {
                return ResourceManager.GetString("spanBuscadorTablasTipos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar usuario.
        /// </summary>
        public static string spanBuscadorUsuarios {
            get {
                return ResourceManager.GetString("spanBuscadorUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notas de cargo.
        /// </summary>
        public static string spanFacturaNav {
            get {
                return ResourceManager.GetString("spanFacturaNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incidencias.
        /// </summary>
        public static string spanIncidenNav {
            get {
                return ResourceManager.GetString("spanIncidenNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listados.
        /// </summary>
        public static string spanInforNav {
            get {
                return ResourceManager.GetString("spanInforNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accidentalidade.
        /// </summary>
        public static string spanListadoAccidentalidad {
            get {
                return ResourceManager.GetString("spanListadoAccidentalidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Facturación.
        /// </summary>
        public static string spanListadoFacturacion {
            get {
                return ResourceManager.GetString("spanListadoFacturacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menú.
        /// </summary>
        public static string spanMenuNav {
            get {
                return ResourceManager.GetString("spanMenuNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Historial modificacións.
        /// </summary>
        public static string spanModificarDatos {
            get {
                return ResourceManager.GetString("spanModificarDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Panel de control.
        /// </summary>
        public static string spanPanelDeControl {
            get {
                return ResourceManager.GetString("spanPanelDeControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reaxuste de datos.
        /// </summary>
        public static string spanReajustarDatos {
            get {
                return ResourceManager.GetString("spanReajustarDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rexistro.
        /// </summary>
        public static string spanRegisNav {
            get {
                return ResourceManager.GetString("spanRegisNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rexistrar grupo.
        /// </summary>
        public static string spanRegistroGrupos {
            get {
                return ResourceManager.GetString("spanRegistroGrupos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rexistrar usuario.
        /// </summary>
        public static string spanRegistroUsuarios {
            get {
                return ResourceManager.GetString("spanRegistroUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rexistro seguinte.
        /// </summary>
        public static string spanSiguienteRegistro {
            get {
                return ResourceManager.GetString("spanSiguienteRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contrasinal.
        /// </summary>
        public static string strContraseña {
            get {
                return ResourceManager.GetString("strContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string strUsuario {
            get {
                return ResourceManager.GetString("strUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vai rematar a sesión.
        /// </summary>
        public static string tituloSesionCaducada {
            get {
                return ResourceManager.GetString("tituloSesionCaducada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a venres.
        /// </summary>
        public static string viernes {
            get {
                return ResourceManager.GetString("viernes", resourceCulture);
            }
        }
    }
}
