//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstiloLibreFront.Traducciones.TrConocenos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TrConocenos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TrConocenos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EstiloLibreFront.Traducciones.TrConocenos.TrConocenos", typeof(TrConocenos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse Gratis.
        /// </summary>
        public static string btnRegistrarseGratis {
            get {
                return ResourceManager.GetString("btnRegistrarseGratis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver al Inicio.
        /// </summary>
        public static string btnVolverAlInicio {
            get {
                return ResourceManager.GetString("btnVolverAlInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Listo para comenzar tu viaje con EstiloLibre?.
        /// </summary>
        public static string lblAccionPregunta {
            get {
                return ResourceManager.GetString("lblAccionPregunta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ahorra Dinero.
        /// </summary>
        public static string lblAhorraDinero {
            get {
                return ResourceManager.GetString("lblAhorraDinero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ahorra Tiempo.
        /// </summary>
        public static string lblAhorraTiempo {
            get {
                return ResourceManager.GetString("lblAhorraTiempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Evita compras duplicadas y toma decisiones de compra más informadas..
        /// </summary>
        public static string lblDescAhorraDinero {
            get {
                return ResourceManager.GetString("lblDescAhorraDinero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Planifica tus outfits con anticipación y elimina el estrés de decidir qué ponerte..
        /// </summary>
        public static string lblDescAhorraTiempo {
            get {
                return ResourceManager.GetString("lblDescAhorraTiempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Analiza tus patrones y preferencias para definir mejor tu estilo personal..
        /// </summary>
        public static string lblDescDescubreTuEstilo {
            get {
                return ResourceManager.GetString("lblDescDescubreTuEstilo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EstiloLibre es para todos, sin importar tu estilo, talla o presupuesto..
        /// </summary>
        public static string lblDescInclusividad {
            get {
                return ResourceManager.GetString("lblDescInclusividad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mejoramos constantemente nuestra plataforma con tecnología de vanguardia..
        /// </summary>
        public static string lblDescInnovacion {
            get {
                return ResourceManager.GetString("lblDescInnovacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reduce el desperdicio textil al maximizar el uso de las prendas que ya posees..
        /// </summary>
        public static string lblDescModaSostenible {
            get {
                return ResourceManager.GetString("lblDescModaSostenible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tus datos son tuyos. Respetamos tu privacidad y protegemos tu información..
        /// </summary>
        public static string lblDescPrivacidad {
            get {
                return ResourceManager.GetString("lblDescPrivacidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Diseñamos herramientas intuitivas que hacen fácil lo complejo..
        /// </summary>
        public static string lblDescSimplicidad {
            get {
                return ResourceManager.GetString("lblDescSimplicidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Promovemos un consumo responsable ayudándote a aprovechar al máximo lo que ya tienes..
        /// </summary>
        public static string lblDescSostenibilidad {
            get {
                return ResourceManager.GetString("lblDescSostenibilidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descubre tu Estilo.
        /// </summary>
        public static string lblDescubreTuEstilo {
            get {
                return ResourceManager.GetString("lblDescubreTuEstilo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EstiloLibre nació de una necesidad común: la dificultad de gestionar un armario lleno de prendas y la sensación constante de &quot;no tener nada que ponerme&quot; a pesar de tener el armario lleno..
        /// </summary>
        public static string lblHistoriaParrafo1 {
            get {
                return ResourceManager.GetString("lblHistoriaParrafo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tras años de experiencia en tecnología y moda, nuestro equipo decidió crear una solución que 
        ///combinara ambos mundos. Así nació EstiloLibre: una aplicación que te ayuda a visualizar todas 
        ///tus prendas, crear combinaciones y optimizar tu guardarropa..
        /// </summary>
        public static string lblHistoriaParrafo2 {
            get {
                return ResourceManager.GetString("lblHistoriaParrafo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hoy, miles de usuarios confían en EstiloLibre para organizar su estilo personal y tomar 
        ///decisiones más conscientes sobre su forma de vestir..
        /// </summary>
        public static string lblHistoriaParrafo3 {
            get {
                return ResourceManager.GetString("lblHistoriaParrafo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empoderar a las personas para que tomen el control de su guardarropa, reduciendo el 
        ///desperdicio textil y fomentando un consumo más consciente y sostenible. Queremos que 
        ///cada usuario descubra el verdadero potencial de su armario..
        /// </summary>
        public static string lblMisionDescripcion {
            get {
                return ResourceManager.GetString("lblMisionDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Moda Sostenible.
        /// </summary>
        public static string lblModaSostenible {
            get {
                return ResourceManager.GetString("lblModaSostenible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuestra Historia.
        /// </summary>
        public static string lblNuestraHistoria {
            get {
                return ResourceManager.GetString("lblNuestraHistoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuestra Misión.
        /// </summary>
        public static string lblNuestraMision {
            get {
                return ResourceManager.GetString("lblNuestraMision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuestra Visión.
        /// </summary>
        public static string lblNuestraVision {
            get {
                return ResourceManager.GetString("lblNuestraVision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuestros Valores.
        /// </summary>
        public static string lblNuestrosValores {
            get {
                return ResourceManager.GetString("lblNuestrosValores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Por qué EstiloLibre?.
        /// </summary>
        public static string lblPorQueEstiloLibre {
            get {
                return ResourceManager.GetString("lblPorQueEstiloLibre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuestra misión es simplificar la forma en que organizas y disfrutas de tu guardarropa.
        /// </summary>
        public static string lblSubTitulo {
            get {
                return ResourceManager.GetString("lblSubTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conócenos.
        /// </summary>
        public static string lblTitulo {
            get {
                return ResourceManager.GetString("lblTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inclusividad.
        /// </summary>
        public static string lblValorInclusividad {
            get {
                return ResourceManager.GetString("lblValorInclusividad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Innovación.
        /// </summary>
        public static string lblValorInnovacion {
            get {
                return ResourceManager.GetString("lblValorInnovacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Privacidad.
        /// </summary>
        public static string lblValorPrivacidad {
            get {
                return ResourceManager.GetString("lblValorPrivacidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Simplicidad.
        /// </summary>
        public static string lblValorSimplicidad {
            get {
                return ResourceManager.GetString("lblValorSimplicidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sostenibilidad.
        /// </summary>
        public static string lblValorSostenibilidad {
            get {
                return ResourceManager.GetString("lblValorSostenibilidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ser la plataforma líder en gestión de guardarropa digital, reconocida por ayudar a 
        ///millones de personas a expresar su estilo personal de forma sostenible y eficiente, 
        ///transformando la relación entre las personas y su ropa..
        /// </summary>
        public static string lblVisionDescripcion {
            get {
                return ResourceManager.GetString("lblVisionDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conócenos.
        /// </summary>
        public static string pagetitle {
            get {
                return ResourceManager.GetString("pagetitle", resourceCulture);
            }
        }
    }
}
