//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstiloLibreFront.Traducciones.TrInicio {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TrInicio {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TrInicio() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EstiloLibreFront.Traducciones.TrInicio.TrInicio", typeof(TrInicio).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comenzar Gratis.
        /// </summary>
        public static string btnComenzar {
            get {
                return ResourceManager.GetString("btnComenzar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Saber más.
        /// </summary>
        public static string btnSaberMas {
            get {
                return ResourceManager.GetString("btnSaberMas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EstiloLibre.
        /// </summary>
        public static string EstiloLibre {
            get {
                return ResourceManager.GetString("EstiloLibre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Organiza tu armario, .
        /// </summary>
        public static string lblGancho1 {
            get {
                return ResourceManager.GetString("lblGancho1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a crea tu estilo.
        /// </summary>
        public static string lblGancho2 {
            get {
                return ResourceManager.GetString("lblGancho2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paso 1.
        /// </summary>
        public static string lblPaso1 {
            get {
                return ResourceManager.GetString("lblPaso1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paso 2.
        /// </summary>
        public static string lblPaso2 {
            get {
                return ResourceManager.GetString("lblPaso2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paso 3.
        /// </summary>
        public static string lblPaso3 {
            get {
                return ResourceManager.GetString("lblPaso3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Listo!.
        /// </summary>
        public static string lblPaso4 {
            get {
                return ResourceManager.GetString("lblPaso4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Listo para transformar tu armario?.
        /// </summary>
        public static string lblSeccionAccion {
            get {
                return ResourceManager.GetString("lblSeccionAccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por qué elegir.
        /// </summary>
        public static string lblSeccionCaracteristicas {
            get {
                return ResourceManager.GetString("lblSeccionCaracteristicas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cómo Funciona.
        /// </summary>
        public static string lblSeccionFuncionamiento {
            get {
                return ResourceManager.GetString("lblSeccionFuncionamiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EstiloLibre es tu asistente personal de moda que te ayuda a gestionar tu guardarropa,
        ///crear conjuntos únicos y descubrir tu estilo personal..
        /// </summary>
        public static string lblSubTituloGancho {
            get {
                return ResourceManager.GetString("lblSubTituloGancho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Únete a miles de usuarios que ya están organizando su estilo con EstiloLibre.
        /// </summary>
        public static string lblTextoAccion {
            get {
                return ResourceManager.GetString("lblTextoAccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Digitaliza todas tus prendas de forma sencilla. Clasifícalas por tipo, color,
        ///temporada y más. Ten tu armario siempre contigo..
        /// </summary>
        public static string lblTextoCaracteristica1 {
            get {
                return ResourceManager.GetString("lblTextoCaracteristica1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Combina tus prendas para crear looks únicos. Guarda tus conjuntos favoritos
        ///y tenlos listos para cualquier ocasión..
        /// </summary>
        public static string lblTextoCaracteristica2 {
            get {
                return ResourceManager.GetString("lblTextoCaracteristica2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Analiza tus preferencias y descubre patrones en tu forma de vestir.
        ///Optimiza tus compras y aprovecha al máximo tu guardarropa..
        /// </summary>
        public static string lblTextoCaracteristica3 {
            get {
                return ResourceManager.GetString("lblTextoCaracteristica3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crea tu cuenta gratuita en menos de un minuto. No necesitas tarjeta de crédito..
        /// </summary>
        public static string lblTextoPaso1 {
            get {
                return ResourceManager.GetString("lblTextoPaso1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fotografía tus prendas o sube imágenes existentes. Añade detalles como color,
        ///tipo y temporada..
        /// </summary>
        public static string lblTextoPaso2 {
            get {
                return ResourceManager.GetString("lblTextoPaso2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Combina tus prendas para crear looks completos. Guarda tus favoritos y
        ///compártelos si quieres..
        /// </summary>
        public static string lblTextoPaso3 {
            get {
                return ResourceManager.GetString("lblTextoPaso3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accede a tu armario digital desde cualquier lugar y nunca más te quedes sin
        ///ideas para vestir..
        /// </summary>
        public static string lblTextoPaso4 {
            get {
                return ResourceManager.GetString("lblTextoPaso4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Organiza tu Armario.
        /// </summary>
        public static string lblTituloCaracteristica1 {
            get {
                return ResourceManager.GetString("lblTituloCaracteristica1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crea Conjuntos.
        /// </summary>
        public static string lblTituloCaracteristica2 {
            get {
                return ResourceManager.GetString("lblTituloCaracteristica2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descubre tu Estilo.
        /// </summary>
        public static string lblTituloCaracteristica3 {
            get {
                return ResourceManager.GetString("lblTituloCaracteristica3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regístrate.
        /// </summary>
        public static string lblTituloPaso1 {
            get {
                return ResourceManager.GetString("lblTituloPaso1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sube tus Prendas.
        /// </summary>
        public static string lblTituloPaso2 {
            get {
                return ResourceManager.GetString("lblTituloPaso2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crea Conjuntos.
        /// </summary>
        public static string lblTituloPaso3 {
            get {
                return ResourceManager.GetString("lblTituloPaso3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disfruta de tu Estilo.
        /// </summary>
        public static string lblTituloPaso4 {
            get {
                return ResourceManager.GetString("lblTituloPaso4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EstiloLibre.
        /// </summary>
        public static string pageTitle {
            get {
                return ResourceManager.GetString("pageTitle", resourceCulture);
            }
        }
    }
}
