//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstiloLibreFront.Traducciones.TrShared {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TrShared {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TrShared() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EstiloLibreFront.Traducciones.TrShared.TrShared", typeof(TrShared).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        public static string btnIniciarSesion {
            get {
                return ResourceManager.GetString("btnIniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse.
        /// </summary>
        public static string btnRegistrarse {
            get {
                return ResourceManager.GetString("btnRegistrarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EstiloLibre.
        /// </summary>
        public static string EstiloLibre {
            get {
                return ResourceManager.GetString("EstiloLibre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ajustes.
        /// </summary>
        public static string lblAjustes {
            get {
                return ResourceManager.GetString("lblAjustes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar sesión.
        /// </summary>
        public static string lblCerrarSesion {
            get {
                return ResourceManager.GetString("lblCerrarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Controis de prenda seleccionada:.
        /// </summary>
        public static string lblControladorCanvas {
            get {
                return ResourceManager.GetString("lblControladorCanvas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Haz clic en una prenda para seleccionarla y poder editarla..
        /// </summary>
        public static string lblExplicacionCanvas {
            get {
                return ResourceManager.GetString("lblExplicacionCanvas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Arrastra las prendas con el mouse o usa los botones. Doble clic para eliminar..
        /// </summary>
        public static string lblExplicacionCanvasPrendaSeleccionada {
            get {
                return ResourceManager.GetString("lblExplicacionCanvasPrendaSeleccionada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu asistente personal de moda. Organiza tu armario, crea conjuntos únicos y descubre tu estilo..
        /// </summary>
        public static string lblFraseGancho {
            get {
                return ResourceManager.GetString("lblFraseGancho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a © 2025 EstiloLibre. Todos los derechos reservados..
        /// </summary>
        public static string lblLicencia {
            get {
                return ResourceManager.GetString("lblLicencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menú.
        /// </summary>
        public static string lblMenu {
            get {
                return ResourceManager.GetString("lblMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conócenos.
        /// </summary>
        public static string nvlkConocenos {
            get {
                return ResourceManager.GetString("nvlkConocenos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contacto.
        /// </summary>
        public static string nvlkContacto {
            get {
                return ResourceManager.GetString("nvlkContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear conjunto.
        /// </summary>
        public static string nvlkCrearConjunto {
            get {
                return ResourceManager.GetString("nvlkCrearConjunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear prenda.
        /// </summary>
        public static string nvlkCrearPrenda {
            get {
                return ResourceManager.GetString("nvlkCrearPrenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio.
        /// </summary>
        public static string nvlkInicio {
            get {
                return ResourceManager.GetString("nvlkInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mis conjuntos.
        /// </summary>
        public static string nvlkListaConjuntos {
            get {
                return ResourceManager.GetString("nvlkListaConjuntos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mis prendas.
        /// </summary>
        public static string nvlkListaPrendas {
            get {
                return ResourceManager.GetString("nvlkListaPrendas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Política de privacidad.
        /// </summary>
        public static string nvlkPoliticaPrivacidad {
            get {
                return ResourceManager.GetString("nvlkPoliticaPrivacidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        public static string phBuscar {
            get {
                return ResourceManager.GetString("phBuscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string ttEliminar {
            get {
                return ResourceManager.GetString("ttEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Baixar prenda.
        /// </summary>
        public static string ttFlechaBajar {
            get {
                return ResourceManager.GetString("ttFlechaBajar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mover derecha.
        /// </summary>
        public static string ttFlechaDerecha {
            get {
                return ResourceManager.GetString("ttFlechaDerecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mover esquerda.
        /// </summary>
        public static string ttFlechaIzquierda {
            get {
                return ResourceManager.GetString("ttFlechaIzquierda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subir prenda.
        /// </summary>
        public static string ttFlechaSubir {
            get {
                return ResourceManager.GetString("ttFlechaSubir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rotar derecha.
        /// </summary>
        public static string ttGirarDerecha {
            get {
                return ResourceManager.GetString("ttGirarDerecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rotar izquierda.
        /// </summary>
        public static string ttGirarIzquierda {
            get {
                return ResourceManager.GetString("ttGirarIzquierda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disminuir.
        /// </summary>
        public static string ttZoomNegativo {
            get {
                return ResourceManager.GetString("ttZoomNegativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aumentar.
        /// </summary>
        public static string ttZoomPositivo {
            get {
                return ResourceManager.GetString("ttZoomPositivo", resourceCulture);
            }
        }
    }
}
